package tab2mxl;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class DrumParserTest {
	
	String fileContent;
	String expected;
	
	@BeforeAll
	static void setUp() throws Exception {
		new Main();
		Main.main(null);
	}

	@Test
	void test() {
	
	
	String path = "ParserTests/tester.musicxml";
	
	String textField ="C |x---------------|--------x-------|x---------------|--------x-------|\n"
					+ "HH|--x-x-x-x-x-x-x-|----------------|--x-x-x-x-x-x-x-|----------------|\n"
					+ "SD|----o-------o---|oooo------------|----o-------o---|oooo------------|\n"
					+ "HT|----------------|----oo----------|----------------|----oo----------|\n"
					+ "T |----------------|------oo--------|----------------|----oo----------|\n"
					+ "T2|o-------o-------|o-------o-------|----------------|----oo----------|";
	

	String[] inputText = textField.split("\n");
	ArrayList<ArrayList<String>> input = GetInput(inputText);
	DrumParser.path = path;
	new DrumParser(input);
	
	
	fileContent = this.readFile(path);
	expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
			+ "<score-partwise version=\"3.1\">\r\n"
			+ "  <work>\r\n"
			+ "    <work-title>Title</work-title>\r\n"
			+ "  </work>\r\n"
			+ "  <part-list>\r\n"
			+ "    <score-part id=\"P1\">\r\n"
			+ "      <part-name>Drumset</part-name>\r\n"
			+ "      <score-instrument id=\"P1-I36\">\r\n"
			+ "        <instrument-name>Bass Drum 1</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I37\">\r\n"
			+ "        <instrument-name>Bass Drum 2</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I38\">\r\n"
			+ "        <instrument-name>Side Stick</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I39\">\r\n"
			+ "        <instrument-name>Snare</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I42\">\r\n"
			+ "        <instrument-name>Low Floor Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I43\">\r\n"
			+ "        <instrument-name>Closed Hi-Hat</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I44\">\r\n"
			+ "        <instrument-name>High Floor Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I45\">\r\n"
			+ "        <instrument-name>Pedal Hi-Hat</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I46\">\r\n"
			+ "        <instrument-name>Low Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I47\">\r\n"
			+ "        <instrument-name>Open Hi-Hat</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I48\">\r\n"
			+ "        <instrument-name>Low-Mid Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I49\">\r\n"
			+ "        <instrument-name>Hi-Mid Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I50\">\r\n"
			+ "        <instrument-name>Crash Cymbal 1</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I51\">\r\n"
			+ "        <instrument-name>High Tom</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I52\">\r\n"
			+ "        <instrument-name>Ride Cymbal 1</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I53\">\r\n"
			+ "        <instrument-name>Chinese Cymbal</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I54\">\r\n"
			+ "        <instrument-name>Ride Bell</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I55\">\r\n"
			+ "        <instrument-name>Tambourine</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I56\">\r\n"
			+ "        <instrument-name>Splash Cymbal</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I57\">\r\n"
			+ "        <instrument-name>Cowbell</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I58\">\r\n"
			+ "        <instrument-name>Crash Cymbal 2</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I60\">\r\n"
			+ "        <instrument-name>Ride Cymbal 2</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I64\">\r\n"
			+ "        <instrument-name>Open Hi Conga</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "      <score-instrument id=\"P1-I65\">\r\n"
			+ "        <instrument-name>Low Conga</instrument-name>\r\n"
			+ "      </score-instrument>\r\n"
			+ "    </score-part>\r\n"
			+ "  </part-list>\r\n"
			+ "  <part id=\"P1\">\r\n"
			+ "    <measure number=\"1\">\r\n"
			+ "      <attributes>\r\n"
			+ "        <divisions>4</divisions>\r\n"
			+ "        <key>\r\n"
			+ "          <fifths>0</fifths>\r\n"
			+ "        </key>\r\n"
			+ "        <time>\r\n"
			+ "          <beats>4</beats>\r\n"
			+ "          <beat-type>4</beat-type>\r\n"
			+ "        </time>\r\n"
			+ "        <clef>\r\n"
			+ "          <sign>percussion</sign>\r\n"
			+ "          <line>2</line>\r\n"
			+ "        </clef>\r\n"
			+ "      </attributes>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>A</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I50\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <backup>\r\n"
			+ "        <duration>16</duration>\r\n"
			+ "      </backup>\r\n"
			+ "    </measure>\r\n"
			+ "    <measure number=\"2\">\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>8</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>half</type>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>A</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>8</duration>\r\n"
			+ "        <instrument id=\"P1-I50\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>half</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <backup>\r\n"
			+ "        <duration>16</duration>\r\n"
			+ "      </backup>\r\n"
			+ "    </measure>\r\n"
			+ "    <measure number=\"3\">\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>A</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I50\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>G</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>2</duration>\r\n"
			+ "        <instrument id=\"P1-I43\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <backup>\r\n"
			+ "        <duration>16</duration>\r\n"
			+ "      </backup>\r\n"
			+ "    </measure>\r\n"
			+ "    <measure number=\"4\">\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">continue</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>C</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I39\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      <beam number=\"1\">begin</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>1</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>16th</type>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>D</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>3</duration>\r\n"
			+ "        <instrument id=\"P1-I46\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <dot/>\r\n"
			+ "      <beam number=\"1\">end</beam>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>3</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <dot/>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <chord/>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>E</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>3</duration>\r\n"
			+ "        <instrument id=\"P1-I48\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>eighth</type>\r\n"
			+ "        <dot/>\r\n"
			+ "      </note>\r\n"
			+ "      <note>\r\n"
			+ "        <unpitched>\r\n"
			+ "          <display-step>A</display-step>\r\n"
			+ "          <display-octave>5</display-octave>\r\n"
			+ "          </unpitched>\r\n"
			+ "        <duration>8</duration>\r\n"
			+ "        <instrument id=\"P1-I50\"/>\r\n"
			+ "        <voice>1</voice>\r\n"
			+ "        <type>half</type>\r\n"
			+ "        <notehead>x</notehead>\r\n"
			+ "      </note>\r\n"
			+ "      <backup>\r\n"
			+ "        <duration>16</duration>\r\n"
			+ "      </backup>\r\n"
			+ "    </measure>\r\n"
			+ "  </part>\r\n"
			+ "</score-partwise>";
	
	expected = expected.replaceAll("\\r", "");
	assertEquals(expected, fileContent);
		
	}
	
	private ArrayList<ArrayList<String>> GetInput (String[] textInput)
	{		
		
		ArrayList<ArrayList<String>> input = new ArrayList<ArrayList<String>>();
		
		for (String line : textInput) {
			if(line.length() > 1)
			{
				line = cleanTextContent(line); //Removes redundant spaces
								
				String[] lineInput = line.substring(line.indexOf('|')).split("");
				ArrayList<String> lineInputList = new ArrayList<String>();
				String tunePlusOctave = line.substring(0, line.indexOf('|')).trim();
				String tune = "";
				String octave = "";
				if(tunePlusOctave.length() > 0) {
					try {
						octave = "" + Integer.parseInt(tunePlusOctave.substring(tunePlusOctave.length()-1));
						tune = tunePlusOctave.substring(0, tunePlusOctave.length()-1);
					}catch(NumberFormatException e1){
						octave = "";
						tune = tunePlusOctave;
					}
				}
				lineInputList.add(tune.trim());
				lineInputList.add(octave.trim());
				//lineInputList.add(tune);
				for(String character : lineInput) {
					lineInputList.add(character);
			    }
				
				input.add(lineInputList);
			}
			else
			{
				input.add(new ArrayList<String>());
			}
		}
		
		return input;
	}
	
	private static String cleanTextContent(String text) 
	{
	    // strips off all non-ASCII characters
	    text = text.replaceAll("[^\\x00-\\x7F]", "");
	 
	    // erases all the ASCII control characters
	    text = text.replaceAll("[\\p{Cntrl}&&[^\r\n\t]]", "");
	    // removes non-printable characters from Unicode
	    text = text.replaceAll("\\p{C}", "");
	    return text.trim();
	}
	
	@SuppressWarnings("resource")
	String readFile(String path) {
		String fileContent = null;
		try {
			fileContent = new Scanner(new File(path)).useDelimiter("\\Z").next();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		return fileContent;
	}

}
