package tab2mxl;

import static org.junit.jupiter.api.Assertions.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class ParserTest {
	
	String fileContent;
	String expected;
	
	@BeforeAll
	static void setUp() {
		new Main();
		Main.main(null);
	}
		
	@Test
	void testParser1() {
		String path = "ParserTests/tester.musicxml";
		
		String textField = "|-----------0-----|-0---------------|\n"
						 + "|---------0---0---|-0---------------|\n"
						 + "|-------1-------1-|-1---------------|\n"
						 + "|-----2-----------|-2---------------|\n"
						 + "|---2-------------|-2---------------|\n"
						 + "|-0---------------|-0---------------|";
		
		String[] inputText = textField.split("\n");
		
		ArrayList<ArrayList<String>> input = GetInput(inputText);		
		new Parser(input, 0, path);
		
		fileContent = this.readFile(path);
		expected ="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <work>\r\n"
				+ "    <work-title>Title</work-title>\r\n"
				+ "  </work>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Guitar</part-name>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>4</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "          <mode>major</mode>\r\n"
				+ "        </key>\r\n"
				+ "        <time>\r\n"
				+ "          <beats>4</beats>\r\n"
				+ "          <beat-type>4</beat-type>\r\n"
				+ "        </time>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>G</sign>\r\n"
				+ "          <line>2</line>\r\n"
				+ "          <clef-octave-change>-1</clef-octave-change>\r\n"
				+ "        </clef>\r\n"
				+ "        <staff-details>\r\n"
				+ "          <staff-lines>6</staff-lines>\r\n"
				+ "          <staff-tuning line=\"1\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"2\">\r\n"
				+ "            <tuning-step>A</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"3\">\r\n"
				+ "            <tuning-step>D</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"4\">\r\n"
				+ "            <tuning-step>G</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"5\">\r\n"
				+ "            <tuning-step>B</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"6\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>4</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "        </staff-details>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>6</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>5</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <accidental>sharp</accidental>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <accidental>sharp</accidental>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>6</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>5</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>2</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <accidental>sharp</accidental>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <chord/>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "          </pitch>\r\n"
				+ "        <duration>16</duration>\r\n"
				+ "        <type>whole</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>";
		
		expected = expected.replaceAll("\\r", "");
		assertEquals(expected, fileContent);
	}

	@Test
	void testParser2() {
		String path = "ParserTests/tester.musicxml";
		
		String textField = "e|-----------------|-----------3h6---|\n"
						 + "B|-----------------|---5h8h5h8-------|\n"
						 + "G|---------------7-|-----------------|\n"
						 + "D|---------5h7h9---|-----------------|\n"
						 + "A|-----5h7---------|-----------------|\n"
						 + "E|-5h8-------------|-----------------|";
		
		String[] inputText = textField.split("\n");
		ArrayList<ArrayList<String>> input = GetInput(inputText);
		new Parser(input, 0, path);
		
		fileContent = this.readFile(path);
		expected ="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <work>\r\n"
				+ "    <work-title>Title</work-title>\r\n"
				+ "  </work>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Guitar</part-name>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>4</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "          <mode>major</mode>\r\n"
				+ "        </key>\r\n"
				+ "        <time>\r\n"
				+ "          <beats>4</beats>\r\n"
				+ "          <beat-type>4</beat-type>\r\n"
				+ "        </time>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>G</sign>\r\n"
				+ "          <line>2</line>\r\n"
				+ "          <clef-octave-change>-1</clef-octave-change>\r\n"
				+ "        </clef>\r\n"
				+ "        <staff-details>\r\n"
				+ "          <staff-lines>6</staff-lines>\r\n"
				+ "          <staff-tuning line=\"1\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"2\">\r\n"
				+ "            <tuning-step>A</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"3\">\r\n"
				+ "            <tuning-step>D</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"4\">\r\n"
				+ "            <tuning-step>G</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"5\">\r\n"
				+ "            <tuning-step>B</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"6\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>4</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "        </staff-details>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>2</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>6</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" placement=\"above\" type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <string>6</string>\r\n"
				+ "            <fret>8</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>5</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" placement=\"above\" type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <string>5</string>\r\n"
				+ "            <fret>7</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" placement=\"above\" type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>7</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>B</step>\r\n"
				+ "          <octave>3</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <string>4</string>\r\n"
				+ "            <fret>9</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>3</string>\r\n"
				+ "            <fret>7</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" placement=\"above\" type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>8</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>5</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>eighth</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>8</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"start\">H</hammer-on>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" placement=\"above\" type=\"start\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>A</step>\r\n"
				+ "          <alter>1</alter>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <accidental>sharp</accidental>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <hammer-on number=\"1\" type=\"stop\"/>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>6</fret>\r\n"
				+ "          </technical>\r\n"
				+ "          <slur number=\"1\" type=\"stop\"/>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>";
		
		expected = expected.replaceAll("\\r", "");
		assertEquals(expected, fileContent);
	}
	
	@Test
	void testParser3() {
		String path = "ParserTests/tester.musicxml";
		
		String textField = "e|-0-------|-0-0-0---|---------|-0-3-3---|-0-------|-0-0-0---|-----3---|-0-------|\n"
						 + "B|---3-1-3-|---------|-3-3-3---|---------|---3-1-3-|---------|-3-------|---1-----|\n"
						 + "G|---------|---------|---------|---------|---------|---------|---------|---------|\n"
						 + "D|---------|---------|---------|---------|---------|---------|---------|---------|\n"
						 + "A|---------|---------|---------|---------|---------|---------|---------|---------|\n"
						 + "E|---------|---------|---------|---------|---------|---------|---------|---------|";
		
		String[] inputText = textField.split("\n");
		ArrayList<ArrayList<String>> input = GetInput(inputText);
		new Parser(input, 0, path);
		
		fileContent = this.readFile(path);
		expected ="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
				+ "<score-partwise version=\"3.1\">\r\n"
				+ "  <work>\r\n"
				+ "    <work-title>Title</work-title>\r\n"
				+ "  </work>\r\n"
				+ "  <part-list>\r\n"
				+ "    <score-part id=\"P1\">\r\n"
				+ "      <part-name>Guitar</part-name>\r\n"
				+ "    </score-part>\r\n"
				+ "  </part-list>\r\n"
				+ "  <part id=\"P1\">\r\n"
				+ "    <measure number=\"1\">\r\n"
				+ "      <attributes>\r\n"
				+ "        <divisions>2</divisions>\r\n"
				+ "        <key>\r\n"
				+ "          <fifths>0</fifths>\r\n"
				+ "          <mode>major</mode>\r\n"
				+ "        </key>\r\n"
				+ "        <time>\r\n"
				+ "          <beats>4</beats>\r\n"
				+ "          <beat-type>4</beat-type>\r\n"
				+ "        </time>\r\n"
				+ "        <clef>\r\n"
				+ "          <sign>G</sign>\r\n"
				+ "          <line>2</line>\r\n"
				+ "          <clef-octave-change>-1</clef-octave-change>\r\n"
				+ "        </clef>\r\n"
				+ "        <staff-details>\r\n"
				+ "          <staff-lines>6</staff-lines>\r\n"
				+ "          <staff-tuning line=\"1\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"2\">\r\n"
				+ "            <tuning-step>A</tuning-step>\r\n"
				+ "            <tuning-octave>2</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"3\">\r\n"
				+ "            <tuning-step>D</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"4\">\r\n"
				+ "            <tuning-step>G</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"5\">\r\n"
				+ "            <tuning-step>B</tuning-step>\r\n"
				+ "            <tuning-octave>3</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "          <staff-tuning line=\"6\">\r\n"
				+ "            <tuning-step>E</tuning-step>\r\n"
				+ "            <tuning-octave>4</tuning-octave>\r\n"
				+ "          </staff-tuning>\r\n"
				+ "        </staff-details>\r\n"
				+ "      </attributes>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"2\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"3\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"4\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"5\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"6\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"7\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>D</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>G</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>4</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>3</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "    <measure number=\"8\">\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>E</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>2</duration>\r\n"
				+ "        <type>quarter</type>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>1</string>\r\n"
				+ "            <fret>0</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "      <note>\r\n"
				+ "        <pitch>\r\n"
				+ "          <step>C</step>\r\n"
				+ "          <octave>4</octave>\r\n"
				+ "        </pitch>\r\n"
				+ "        <duration>6</duration>\r\n"
				+ "        <type>half</type>\r\n"
				+ "        <dot/>\r\n"
				+ "        <notations>\r\n"
				+ "          <technical>\r\n"
				+ "            <string>2</string>\r\n"
				+ "            <fret>1</fret>\r\n"
				+ "          </technical>\r\n"
				+ "        </notations>\r\n"
				+ "        <stem>down</stem>\r\n"
				+ "        <staff>1</staff>\r\n"
				+ "      </note>\r\n"
				+ "    </measure>\r\n"
				+ "  </part>\r\n"
				+ "</score-partwise>";
		
		expected = expected.replaceAll("\\r", "");
		assertEquals(expected, fileContent);
	}
	
	@Test
	void testNoteType() {
		assertEquals("whole", Parser.noteType(1.0));
		assertEquals("half", Parser.noteType(1.0/2.0));
		
		assertEquals("quarter", Parser.noteType(1.0/4.0));
		assertEquals("eighth", Parser.noteType(1.0/8.0));
		assertEquals("16th", Parser.noteType(1.0/16.0));
		assertEquals("32nd", Parser.noteType(1.0/32.0));
		assertEquals("64th", Parser.noteType(1.0/64.0));
		assertEquals("128th", Parser.noteType(1.0/128));
		assertEquals("256th", Parser.noteType(1.0/256));
		assertEquals("512th", Parser.noteType(1.0/512));
		assertEquals("1024th", Parser.noteType(1.0/1024));
	}
	
	@Test
	void testAddTitle() {
		Parser.misc = new HashMap<String, String>();
		Parser.addTitle("Test Title");
		
		assertEquals(Parser.misc.get("Title"), "Test Title");
	}

	@Test
	void testAddTabType() {
		Parser.misc = new HashMap<String, String>();
		Parser.addInstrument("Guitar");
		
		assertEquals(Parser.misc.get("Instrument"), "Guitar");
	}

	@Test
	void testAddTime() {
		Parser.misc = new HashMap<String, String>();
		Parser.addTime("4");
		
		assertEquals(Parser.misc.get("TimeSig"), "4");
	}
	
	private ArrayList<ArrayList<String>> GetInput (String[] textInput)
	{		
		
		ArrayList<ArrayList<String>> input = new ArrayList<ArrayList<String>>();
		
		for (String line : textInput) {
			if(line.length() > 1)
			{
				line = cleanTextContent(line); //Removes redundant spaces
								
				String[] lineInput = line.substring(line.indexOf('|')).split("");
				ArrayList<String> lineInputList = new ArrayList<String>();
				String tunePlusOctave = line.substring(0, line.indexOf('|')).trim();
				String tune = "";
				String octave = "";
				if(tunePlusOctave.length() > 0) {
					try {
						octave = "" + Integer.parseInt(tunePlusOctave.substring(tunePlusOctave.length()-1));
						tune = tunePlusOctave.substring(0, tunePlusOctave.length()-1);
					}catch(NumberFormatException e1){
						octave = "";
						tune = tunePlusOctave;
					}
				}
				lineInputList.add(tune.trim());
				lineInputList.add(octave.trim());
				//lineInputList.add(tune);
				for(String character : lineInput) {
					lineInputList.add(character);
			    }
				
				input.add(lineInputList);
			}
			else
			{
				input.add(new ArrayList<String>());
			}
		}
		
		return input;
	}
	
	private static String cleanTextContent(String text) 
	{
	    // strips off all non-ASCII characters
	    text = text.replaceAll("[^\\x00-\\x7F]", "");
	 
	    // erases all the ASCII control characters
	    text = text.replaceAll("[\\p{Cntrl}&&[^\r\n\t]]", "");
	     
	    // removes non-printable characters from Unicode
	    text = text.replaceAll("\\p{C}", "");
	 
	    return text.trim();
	}
	
	@SuppressWarnings("resource")
	String readFile(String path) {
		String fileContent = null;
		try {
			fileContent = new Scanner(new File(path)).useDelimiter("\\Z").next();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
		return fileContent;
	}
}
